name: pharmacypro
description: "PharmaChain - Pharmacy Management System"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^3.13.0
  cloud_firestore: ^5.6.8
  firebase_auth: ^5.5.4
  firebase_app_check: ^0.3.2+3
  firebase_crashlytics: 4.3.10

  # State Management
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  freezed_annotation: ^3.0.0

  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0

  # Routing
  go_router: ^15.1.2

  # Responsive
  flutter_screenutil: ^5.9.3

  # Serialization
  json_annotation: ^4.9.0

  # SVG
  flutter_svg: ^2.0.17

  # Security
  flutter_secure_storage: ^9.2.4

  # Utils
  intl: ^0.20.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^6.0.5
  fluttertoast: ^9.0.0
  flutter_localizations:
    sdk: flutter
  connectivity_plus: ^7.1.1
  shared_preferences: ^2.5.5
  firebase_messaging: ^15.2.10
  flutter_local_notifications: ^21.0.0
  google_mlkit_text_recognition: ^0.15.1
  pdf: ^3.12.0
  printing: ^5.14.3
  share_plus: ^12.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.4.14
  json_serializable: ^6.9.4
  injectable_generator: ^2.7.0
  freezed: ^3.0.0
  mocktail: ^1.0.4
  bloc_test: ^10.0.0
  fake_cloud_firestore: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - lang/en.json
    - lang/ar.json
